-- =====================================================================
-- 05_seed_master_data.sql
-- Chạy trong Supabase SQL Editor sau khi đã chạy 01-04
-- 40 billing_groups | 113 customers
-- =====================================================================

-- BƯỚC 1: Nhóm đối soát

INSERT INTO billing_groups (
  ma_he_thong, ten_nhom, ngung_hop_tac,
  diem_gmv, diem_company_size, diem_tranh_chap, diem_phuc_tap, nhom_escalate,
  ngay_gui_bang_ke_hd, ngay_gui_bang_ke_thuc_te,
  sla_chap_nhan_hd, sla_chap_nhan_thuc_te, sla_phan_hoi_dieu_chinh,
  sla_ky_bien_ban, sla_hstt, payment_term, ho_so_thanh_toan,
  email_l1, email_l2, email_l3, email_ke_toan, email_pm, email_high_level, email_cc
) VALUES
  ('MASTERISE', 'MASTERISE', false,
   3, 3, 2, 2, 2,
   2, 6,
   10, NULL, NULL,
   NULL, NULL, 15, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('EB', 'CENTRAL RETAIL', true,
   NULL, NULL, NULL, NULL, 2,
   30, 6,
   NULL, NULL, NULL,
   NULL, NULL, 25, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('MSB', 'MSB', false,
   3, 3, 2, 2, 2,
   30, 6,
   5, NULL, NULL,
   NULL, NULL, 15, 'Bảng kê ký số',
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('ROX', 'ROX', false,
   3, 3, 2, 2, 2,
   30, 6,
   3, NULL, NULL,
   NULL, NULL, 30, 'Bảng kê, DNTT ký tên đóng dấu',
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('MAGISKATOR', 'MAGISKATOR', true,
   NULL, NULL, NULL, NULL, 2,
   30, 6,
   NULL, NULL, NULL,
   NULL, NULL, 10, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('TOSHIBA', 'TOSHIBA', false,
   3, 2, 3, 2, 2,
   30, 6,
   5, NULL, NULL,
   NULL, NULL, 15, 'Bảng kê chi phí phòng ban ký số, hóa đơn pdf gửi email',
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('VIETCOMBANK', 'VIETCOMBANK', false,
   3, 3, 3, 3, 2,
   30, 6,
   10, NULL, NULL,
   NULL, NULL, 5, 'Bảng kê, DNTT, hóa đơn chuyển đổi ký tên đóng dấu, bảng kê chi tiết hóa đơn, CTP',
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('TPBANK', 'TPBANK', false,
   3, 3, 3, 3, 2,
   1, 6,
   5, NULL, NULL,
   NULL, NULL, 20, 'Bảng kê, DNTT ký số gửi email',
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('AI VIET VENTURE', 'AI VIET VENTURE', false,
   2, 2, 1, 2, 2,
   30, 6,
   2, NULL, NULL,
   NULL, NULL, 10, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('BAN VIET', 'BAN VIET', false,
   2, 2, 2, 2, 2,
   30, 6,
   5, NULL, NULL,
   NULL, NULL, 30, 'Bảng kê ký tên, đóng dấu, Bảng kê hóa đơn chiết khấu',
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('SCG', 'SCG', false,
   2, 2, 2, 2, 2,
   2, 6,
   5, NULL, NULL,
   NULL, NULL, 15, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('UNICHARM', 'UNICHARM', false,
   2, 2, 2, 2, 2,
   1, 6,
   5, NULL, NULL,
   NULL, NULL, 20, 'Bảng kê, DNTT ký số gửi email',
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('Y TUONG VIET', 'Y TUONG VIET', false,
   2, 2, 2, 2, 2,
   16, 6,
   3, NULL, NULL,
   NULL, NULL, 15, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('AGARI01', 'AGARI01', false,
   2, 1, 1, 1, 2,
   30, 6,
   NULL, NULL, NULL,
   NULL, NULL, NULL, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('BAO VIET', 'CK BAO VIET', true,
   2, 1, 1, 1, 2,
   30, 6,
   NULL, NULL, NULL,
   NULL, NULL, NULL, 'Không ký HĐ',
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('COMEX FARM', 'COMEX FARM', true,
   2, 1, 1, 1, 2,
   30, 6,
   NULL, NULL, NULL,
   NULL, NULL, NULL, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('HỪNG ĐÔNG', 'CÔNG NGHỆ HỪNG ĐÔNG', false,
   2, 1, 1, 1, 2,
   30, 6,
   3, NULL, NULL,
   NULL, NULL, 10, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('CRYSTABAYA', 'CRYSTABAYA', true,
   2, 1, 1, 1, 2,
   30, 6,
   NULL, NULL, NULL,
   NULL, NULL, 10, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('CUSHMAN', 'CUSHMAN', false,
   2, 1, 1, 1, 2,
   30, 6,
   7, NULL, NULL,
   NULL, NULL, 30, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('DCORP', 'DCORP', false,
   2, 1, 1, 1, 2,
   30, 6,
   3, NULL, NULL,
   NULL, NULL, 10, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('DOS BUSINESS CONSULTING', 'DOS BUSINESS CONSULTING', false,
   2, 1, 1, 1, 2,
   30, 6,
   2, NULL, NULL,
   NULL, NULL, 10, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('DONG TAM', 'DTG', false,
   2, 1, 1, 1, 2,
   30, 6,
   5, NULL, NULL,
   NULL, NULL, 15, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('FILMORE', 'FILMORE', false,
   2, 1, 1, 1, 2,
   30, 6,
   3, NULL, NULL,
   NULL, NULL, 10, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('HAN''S SPACE', 'HAN''S SPACE', false,
   2, 1, 1, 1, 2,
   30, 6,
   2, NULL, NULL,
   NULL, NULL, 10, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('HAPPYLIVE', 'HAPPY LIVE', false,
   2, 1, 1, 1, 2,
   30, 6,
   2, NULL, NULL,
   NULL, NULL, 10, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('KHACH LE', 'KHACH LE', false,
   2, 1, 1, 1, 2,
   30, 6,
   NULL, NULL, NULL,
   NULL, NULL, 1, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('LAVICOM', 'LAVICOM', false,
   2, 1, 1, 1, 2,
   30, 6,
   3, NULL, NULL,
   NULL, NULL, 10, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('LM CAPITAL', 'LM CAPITAL', false,
   2, 1, 1, 1, 2,
   30, 6,
   2, NULL, NULL,
   NULL, NULL, 10, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('MIDEA', 'MDC', true,
   2, 1, 1, 1, 2,
   30, 6,
   NULL, NULL, NULL,
   NULL, NULL, 20, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('ME KONG', 'ME KONG', false,
   2, 1, 1, 1, 2,
   2, 6,
   2, NULL, NULL,
   NULL, NULL, 15, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('NAM PHONG', 'NAM PHONG', true,
   2, 1, 1, 1, 2,
   30, 6,
   NULL, NULL, NULL,
   NULL, NULL, 7, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('PREECO', 'PREECO', false,
   2, 1, 1, 1, 2,
   30, 6,
   2, NULL, NULL,
   NULL, NULL, 10, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('EVENTX', 'QUICKOM', false,
   2, 1, 1, 1, 2,
   30, 6,
   2, NULL, NULL,
   NULL, NULL, 10, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('TDG', 'TDG', true,
   2, 1, 1, 1, 2,
   30, 6,
   NULL, NULL, NULL,
   NULL, NULL, NULL, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('TEIBTO', 'TEIBTO', false,
   2, 1, 1, 1, 2,
   20, 6,
   4, NULL, NULL,
   NULL, NULL, 15, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('TKF', 'TKF', false,
   2, 1, 1, 1, 2,
   30, 6,
   2, NULL, NULL,
   NULL, NULL, 10, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('CÔNG TY CỔ PHẦN UNIVERSAL TRAVEL SOLUTIONS NETWORK', 'UTS', false,
   2, 1, 1, 1, 2,
   30, 6,
   NULL, NULL, NULL,
   NULL, NULL, NULL, NULL,
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('TEST_GROUP', 'TEST_GROUP', false,
   2, 1, 1, 1, 1,
   7, 10,
   3, 3, 1,
   2, 2, 10, 'Kí ĐNTT',
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('TEST_GROUP2', 'TEST_GROUP2', false,
   2, 1, 1, 1, 2,
   7, 10,
   3, 3, 1,
   2, 2, 10, 'Kí ĐNTT',
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL),
  ('TEST_GROUP3', 'TEST_GROUP3', false,
   2, 1, 1, 1, 3,
   7, 10,
   3, 3, 1,
   2, 2, 10, 'Kí ĐNTT',
   'phuongvan2003.vl+L1@gmail.com', 'phuongvan2003.vl+L2@gmail.com', 'phuongvan2003.vl+L3@gmail.com',
   'phuongvan2003.vl+Accountant@gmail.com', 'phuongvan2003.vl+PM@gmail.com', 'phuongvan2003.vl+High@gmail.com', NULL)
ON CONFLICT (ma_he_thong) DO UPDATE SET
  ten_nhom = EXCLUDED.ten_nhom,
  ngung_hop_tac = EXCLUDED.ngung_hop_tac,
  diem_gmv = EXCLUDED.diem_gmv,
  diem_company_size = EXCLUDED.diem_company_size,
  diem_tranh_chap = EXCLUDED.diem_tranh_chap,
  diem_phuc_tap = EXCLUDED.diem_phuc_tap,
  nhom_escalate = EXCLUDED.nhom_escalate,
  ngay_gui_bang_ke_hd = EXCLUDED.ngay_gui_bang_ke_hd,
  ngay_gui_bang_ke_thuc_te = EXCLUDED.ngay_gui_bang_ke_thuc_te,
  sla_chap_nhan_hd = EXCLUDED.sla_chap_nhan_hd,
  sla_chap_nhan_thuc_te = EXCLUDED.sla_chap_nhan_thuc_te,
  sla_phan_hoi_dieu_chinh = EXCLUDED.sla_phan_hoi_dieu_chinh,
  sla_ky_bien_ban = EXCLUDED.sla_ky_bien_ban,
  sla_hstt = EXCLUDED.sla_hstt,
  payment_term = EXCLUDED.payment_term,
  ho_so_thanh_toan = EXCLUDED.ho_so_thanh_toan,
  email_l1 = EXCLUDED.email_l1,
  email_l2 = EXCLUDED.email_l2,
  email_l3 = EXCLUDED.email_l3,
  email_ke_toan = EXCLUDED.email_ke_toan,
  email_pm = EXCLUDED.email_pm,
  email_high_level = EXCLUDED.email_high_level,
  email_cc = EXCLUDED.email_cc,
  updated_at = now();

-- BƯỚC 2: Pháp nhân trực thuộc

INSERT INTO customers (group_id, ten_khach_hang, ten_viet_tat, ngung_hop_tac)
SELECT bg.id, v.ten, v.vt, v.ng
FROM (VALUES
  ('NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN KỸ THƯƠNG VIỆT NAM', 'TECHCOMBANK', 'MASTERISE', false),
  ('CÔNG TY CỔ PHẦN DỊCH VỤ, THƯƠNG MẠI VÀ ĐẦU TƯ SAO THỦY', 'MASTERISE', 'MASTERISE', false),
  ('CÔNG TY CỔ PHẦN DỊCH VỤ, THƯƠNG MẠI VÀ ĐẦU TƯ SAO THỦY', 'SAO THUY', 'MASTERISE', false),
  ('CÔNG TY TNHH THƯƠNG MẠI QUỐC TẾ VÀ DỊCH VỤ SIÊU THỊ BIG C THĂNG LONG', 'BIG C', 'EB', true),
  ('CÔNG TY TNHH DỊCH VỤ EB', 'EB', 'EB', true),
  ('NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN HÀNG HẢI VIỆT NAM', 'MSB', 'MSB', false),
  ('CÔNG TY CỔ PHẦN TƯ VẤN QUẢN LÝ DỰ ÁN XÂY DỰNG MANPRO', 'MANPRO', 'ROX', false),
  ('CÔNG TY CỔ PHẦN DỊCH VỤ BẢO VỆ NHẤT VIỆT', 'NHAT VIET', 'ROX', false),
  ('CÔNG TY CỔ PHẦN ĐẦU TƯ VÀ CHO THUÊ TÀI SẢN TNL', 'TNL', 'ROX', false),
  ('CÔNG TY CỔ PHẦN TNTECH', 'TNTECH', 'ROX', false),
  ('CÔNG TY CỔ PHẦN ĐẦU TƯ VÀ QUẢN LÝ BẤT ĐỘNG SẢN TN PROPERTY MANAGEMENT', 'TNPM', 'ROX', false),
  ('CÔNG TY CỔ PHẦN ROX KEY HOLDINGS', 'ROX KEY', 'ROX', false),
  ('CÔNG TY CỔ PHẦN TẬP ĐOÀN ROX', 'ROX', 'ROX', false),
  ('CÔNG TY CỔ PHẦN ROX LIVING', 'ROX LIVING', 'ROX', false),
  ('CÔNG TY CỔ PHẦN DỊCH VỤ VỆ SINH CÔNG NGHIỆP C-ONE', 'C-ONE', 'ROX', false),
  ('CÔNG TY CỔ PHẦN THƯƠNG MẠI & TƯ VẤN ĐẤU THẦU, THẨM ĐỊNH GIÁ', 'TNPA', 'ROX', false),
  ('CÔNG TY CỔ PHẦN ĐẦU TƯ VÀ QUẢN LÝ KHÁCH SẠN TNH', 'TNH', 'ROX', false),
  ('CÔNG TY CỔ PHẦN TƯ VẤN ĐẦU TƯ VÀ PHÁT TRIỂN XÂY DỰNG TND', 'TND', 'ROX', false),
  ('CÔNG TY CỔ PHẦN DỊCH VỤ QUẢN LÝ VẬN HÀNH KHU CÔNG NGHIỆP IMC', 'IMC', 'ROX', false),
  ('CÔNG TY CỔ PHẦN ROX ASSET', 'ROX ASSET', 'ROX', false),
  ('CÔNG TY CỔ PHẦN ROX LIVING GLOBAL', 'ROX LIVING GLOBAL', 'ROX', false),
  ('CÔNG TY CỔ PHẦN POPPLIFE', 'POPPLIFE', 'ROX', false),
  ('CÔNG TY CP THƯƠNG MẠI DỊCH VỤ TRỌNG HƯNG', 'TRONG HUNG', 'ROX', false),
  ('CÔNG TY CP DỊCH VỤ THƯƠNG MẠI ĐẦU TƯ HỮU ĐẠT', 'HUU DAT', 'ROX', false),
  ('CÔNG TY CỔ PHẦN ROX CAPITAL', 'ROX CAPITAL', 'ROX', false),
  ('CÔNG TY CỔ PHẦN ROX SIGNATURE', 'ROX SIGNATURE', 'ROX', false),
  ('CÔNG TY CỔ PHẦN NĂNG LƯỢNG TOÀN CẦU ROX', 'ROX NANG LUONG', 'ROX', false),
  ('CÔNG TY CỔ PHẦN MAGISKATOR', 'MAGISKATOR', 'MAGISKATOR', true),
  ('CÔNG TY CỔ PHẦN ĐẦU TƯ ROX ENERGY', 'ROX ENERGY', 'ROX', false),
  ('CÔNG TY TNHH TƯ VẤN VÀ ĐẦU TƯ TẬP ĐOÀN RES', 'RES', 'ROX', false),
  ('CÔNG TY CỔ PHẦN ĐẦU TƯ VÀ PHÁT TRIỂN HẠ TẦNG NAM QUANG', 'NAM QUANG', 'ROX', false),
  ('CÔNG TY CỔ PHẦN NĂNG LƯỢNG LỘC NINH 4', 'LOC NINH', 'ROX', false),
  ('CÔNG TY TNHH ĐIỆN MẶT TRỜI THUẬN NAM 19', 'THUAN NAM', 'ROX', false),
  ('CÔNG TY CỔ PHẦN GREEN ENERGY PHƯỚC HỮU', 'PHUOC HUU', 'ROX', false),
  ('RECA Limited Liability Company', 'RECA', 'ROX', false),
  ('CÔNG TY CP THƯƠNG MẠI VÀ ĐẦU TƯ PHÁT TRIỂN MINH KHANG', 'MINH KHANG', 'ROX', false),
  ('CÔNG TY CỔ PHẦN ĐẦU TƯ PHÚ THÀNH KHANG', 'PHU THANH KHANG', 'ROX', false),
  ('CÔNG TY CỔ PHẦN ĐẦU TƯ PHÁT TRIỂN ROX IPARK VIỆT NAM', 'ROX IPARK', 'ROX', false),
  ('CÔNG TY CỔ PHẦN QUẢN TRỊ NGUỒN NHÂN LỰC TNTALENT', 'TNTALENT', 'ROX', false),
  ('CÔNG TY CỔ PHẦN THƯƠNG MẠI M- TRADING', 'MTRADING', 'ROX', false),
  ('CÔNG TY CỔ PHẦN HANO-VID', 'HANO-VID', 'ROX', false),
  ('RCA Living LLC', 'RCA', 'ROX', false),
  ('CÔNG TY CỔ PHẦN THƯƠNG MẠI - QUẢNG CÁO - XÂY DỰNG - ĐỊA ỐC VIỆT HÂN', 'VIET HAN', 'ROX', false),
  ('CÔNG TY TNHH OLECO - NQ', 'OLECO', 'ROX', false),
  ('CÔNG TY CỔ PHẦN ĐẦU TƯ PHÁT TRIỂN BẤT ĐỘNG SẢN TNR HOLDINGS VIỆT NAM', 'TNR', 'ROX', false),
  ('CÔNG TY TÀI CHÍNH TRÁCH NHIỆM HỮU HẠN MỘT THÀNH VIÊN TNEX', 'TNEX', 'ROX', false),
  ('CÔNG TY TNHH CKC', 'CKC', 'ROX', false),
  ('CÔNG TY TNHH THÀNH PHỐ CÔNG NGHỆ XANH HÀ NỘI', 'CONG NGHE XANH', 'ROX', false),
  ('CÔNG TY CỔ PHẦN MAY - DIÊM SÀI GÒN', 'MAY DIEM SG', 'ROX', false),
  ('CÔNG TY CỔ PHẦN BẤT ĐỘNG SẢN MỸ', 'BDS MY', 'ROX', false),
  ('CÔNG TY TNHH ĐẦU TƯ BẤT ĐỘNG SẢN LONG VÂN', 'LONG VAN', 'ROX', false),
  ('CÔNG TY CỔ PHẦN BẤT ĐỘNG SẢN XÂY DỰNG HƯNG THỊNH', 'HUNG THINH', 'ROX', false),
  ('CÔNG TY CỔ PHẦN KINH DOANH XÂY DỰNG-VẬN TẢI THANH HÀ', 'THANH HA', 'ROX', false),
  ('CÔNG TY CỔ PHẦN XÂY DỰNG VÀ KINH DOANH BẤT ĐỘNG SẢN VĨNH PHÚC', 'VINH PHUC', 'ROX', false),
  ('CÔNG TY TRÁCH NHIỆM HỮU HẠN MỘT THÀNH VIÊN HÙNG LÂM', 'HUNG LAM', 'ROX', false),
  ('CÔNG TY TNHH SẢN PHẨM TIÊU DÙNG TOSHIBA VIỆT NAM', 'TOSHIBA', 'TOSHIBA', false),
  ('CÔNG TY TNHH TOSHIBA LOGISTICS VIỆT NAM', 'TOSHIBA LOGISTICS', 'TOSHIBA', false),
  ('NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN NGOẠI THƯƠNG VIỆT NAM', 'VIETCOMBANK', 'VIETCOMBANK', false),
  ('NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN TIÊN PHONG', 'TPBANK', 'TPBANK', false),
  ('CÔNG TY TNHH MTV QUẢN LÝ NỢ VÀ KHAI THÁC TÀI SẢN NGÂN HÀNG TIÊN PHONG', 'TPBANK', 'TPBANK', false),
  ('CÔNG TY CỔ PHẦN ÁI VIỆT VENTURE', 'AI VIET VENTURE', 'AI VIET VENTURE', false),
  ('NGÂN HÀNG THƯƠNG MẠI CỔ PHẦN BẢN VIỆT', 'BAN VIET', 'BAN VIET', false),
  ('CÔNG TY TNHH SCG VIỆT NAM', 'SCG', 'SCG', false),
  ('CÔNG TY TNHH SCGJWD LOGISTICS (VIỆT NAM)', 'SCG JWD', 'SCG', false),
  ('CÔNG TY CỔ PHẦN DIANA UNICHARM', 'UNICHARM', 'UNICHARM', false),
  ('CHI NHÁNH CÔNG TY CỔ PHẦN DIANA UNICHARM - BẮC NINH', 'UNICHARM', 'UNICHARM', false),
  ('CÔNG TY TNHH THỰC PHẨM & NƯỚC GIẢI KHÁT Ý TƯỞNG VIỆT', 'Y TUONG VIET', 'Y TUONG VIET', false),
  ('CHI NHÁNH CÔNG TY TNHH THỰC PHẨM & NƯỚC GIẢI KHÁT Ý TƯỞNG VIỆT', 'Y TUONG VIET', 'Y TUONG VIET', false),
  ('CHI NHÁNH CÔNG TY TNHH THỰC PHẨM & NƯỚC GIẢI KHÁT Ý TƯỞNG VIỆT TẠI HẢI PHÒNG', 'Y TUONG VIET', 'Y TUONG VIET', false),
  ('CHI NHÁNH CÔNG TY TNHH THỰC PHẨM & NƯỚC GIẢI KHÁT Ý TƯỞNG VIỆT TẠI PHÚ QUỐC', 'Y TUONG VIET', 'Y TUONG VIET', false),
  ('CHI NHÁNH CÔNG TY TNHH THỰC PHẨM & NƯỚC GIẢI KHÁT Ý TƯỞNG VIỆT TẠI TÂY NINH', 'Y TUONG VIET', 'Y TUONG VIET', false),
  ('CHI NHÁNH CÔNG TY TNHH THỰC PHẨM & NƯỚC GIẢI KHÁT Ý TƯỞNG VIỆT TẠI NINH BÌNH', 'Y TUONG VIET', 'Y TUONG VIET', false),
  ('CHI NHÁNH CÔNG TY TNHH THỰC PHẨM & NƯỚC GIẢI KHÁT Ý TƯỞNG VIỆT TẠI HÀ TĨNH', 'Y TUONG VIET', 'Y TUONG VIET', false),
  ('CHI NHÁNH CÔNG TY TNHH THỰC PHẨM & NƯỚC GIẢI KHÁT Ý TƯỞNG VIỆT TẠI AN GIANG', 'Y TUONG VIET', 'Y TUONG VIET', false),
  ('CÔNG TY TNHH SSMX', 'SSMX', 'Y TUONG VIET', false),
  ('CÔNG TY TNHH AGARI', 'AGARI01', 'AGARI01', false),
  ('CÔNG TY CỔ PHẦN CHỨNG KHOÁN BẢO VIỆT', 'CK BAO VIET', 'BAO VIET', true),
  ('CÔNG TY TNHH COMEX FARM', 'COMEX FARM', 'COMEX FARM', true),
  ('CÔNG TY TNHH MỘT THÀNH VIÊN CÔNG NGHỆ HỪNG ĐÔNG', 'CÔNG NGHỆ HỪNG ĐÔNG', 'HỪNG ĐÔNG', false),
  ('CÔNG TY CỔ PHẦN CRYSTABAYA', 'CRYSTABAYA', 'CRYSTABAYA', true),
  ('CÔNG TY TNHH CUSHMAN & WAKEFIELD (VIỆT NAM)', 'CUSHMAN', 'CUSHMAN', false),
  ('CÔNG TY CỔ PHẦN CÔNG NGHỆ DCORP', 'DCORP', 'DCORP', false),
  ('CÔNG TY TNHH CÔNG NGHỆ QUẢN LÝ DOANH THU', 'DOS BUSINESS CONSULTING', 'DOS BUSINESS CONSULTING', false),
  ('CÔNG TY CỔ PHẦN ĐỒNG TÂM DOTALIA', 'DONG TAM DOTALIA', 'DONG TAM', false),
  ('CÔNG TY CỔ PHẦN ĐỒNG TÂM', 'DONG TAM', 'DONG TAM', false),
  ('CÔNG TY CỔ PHẦN PHÁT TRIỂN CHÂU Á', 'PT CHAU A', 'DONG TAM', false),
  ('CÔNG TY TNHH MTV THƯƠNG MẠI ĐỒNG TÂM', 'TM DONG TAM', 'DONG TAM', false),
  ('CÔNG TY CỔ PHẦN CẢNG LONG AN', 'CANG LONG AN', 'DONG TAM', false),
  ('CÔNG TY CỔ PHẦN QUẢN LÝ & KHAI THÁC CẢNG QUỐC TẾ LONG AN', 'CANG QT LONG AN', 'DONG TAM', false),
  ('CÔNG TY CP ĐỒNG TÂM - MIỀN TRUNG', 'DONG TAM MIEN TRUNG', 'DONG TAM', false),
  ('CÔNG TY TNHH ĐỒNG TÂM QUẢNG NGÃI', 'DONG TAM QUANG NGAI', 'DONG TAM', false),
  ('CÔNG TY CỔ PHẦN PHÁT TRIỂN BẤT ĐỘNG SẢN FILMORE', 'FILMORE', 'FILMORE', false),
  ('CÔNG TY CỔ PHẦN HAN''S SPACE', 'HAN''S SPACE', 'HAN''S SPACE', false),
  ('CÔNG TY TNHH HAPPY LIVE', 'HAPPY LIVE', 'HAPPYLIVE', false),
  ('KHÁCH LẺ KHÔNG LẤY HÓA ĐƠN', 'KHACH LE', 'KHACH LE', false),
  ('CÔNG TY TNHH LAVICOM', 'LAVICOM', 'LAVICOM', false),
  ('CÔNG TY CỔ PHẦN CÔNG NGHỆ LAVITEC', 'LAVITEC', 'LAVICOM', false),
  ('CÔNG TY TNHH LM CAPITAL', 'LM CAPITAL', 'LM CAPITAL', false),
  ('CÔNG TY TNHH MD CONSUMER ELECTRIC APPLIANCE VIỆT NAM', 'MDC', 'MIDEA', true),
  ('CÔNG TY CP LƯƠNG THỰC MEKONG', 'ME KONG', 'ME KONG', false),
  ('CÔNG TY TNHH ĐẦU TƯ VÀ PHÁT TRIỂN NAM PHONG HD', 'NAM PHONG', 'NAM PHONG', true),
  ('CÔNG TY TNHH PREECO', 'PREECO', 'PREECO', false),
  ('CÔNG TY TNHH PREECO STUDIO', 'PREECO STUDIO', 'PREECO', false),
  ('CÔNG TY CỔ PHẦN CÔNG NGHỆ QUICKOM', 'QUICKOM', 'EVENTX', false),
  ('CÔNG TY TNHH MTV EVENTX', 'EVENTX', 'EVENTX', false),
  ('CÔNG TY TNHH THẨM ĐỊNH GIÁ HCMC', 'TDG', 'TDG', true),
  ('CÔNG TY TNHH TEIBTO', 'TEIBTO', 'TEIBTO', false),
  ('CÔNG TY CỔ PHẦN THƯƠNG MẠI DỊCH VỤ TKF', 'TKF', 'TKF', false),
  ('CÔNG TY CỔ PHẦN ĐẦU TƯ KCP1', 'KCP1', 'TKF', false),
  ('CÔNG TY CỔ PHẦN UNIVERSAL TRAVEL SOLUTIONS NETWORK', 'UTS', 'CÔNG TY CỔ PHẦN UNIVERSAL TRAVEL SOLUTIONS NETWORK', false),
  ('CÔNG TY TEST GROUP', 'TEST_GROUP', 'TEST_GROUP', false),
  ('CÔNG TY TEST GROUP 2', 'TEST_GROUP2', 'TEST_GROUP2', false),
  ('CÔNG TY TEST GROUP 3', 'TEST_GROUP3', 'TEST_GROUP3', false)
) AS v(ten, vt, ma_he_thong, ng)
JOIN billing_groups bg ON bg.ma_he_thong = v.ma_he_thong
ON CONFLICT DO NOTHING;

-- ✓ Xong: 40 nhóm | 113 pháp nhân